parameters:
  ## memberships_source: "memberships.static", "memberships.csv", "memberships.civicrmorg_http" or "memberships.civicrmorg_sql"
  memberships_ttl: 180

doctrine:
  dbal:
    connections:
      civicrmorg:
        driver:   pdo_mysql
        host:     "%civicrmorg_database_host%"
        port:     "%civicrmorg_database_port%"
        dbname:   "%civicrmorg_database_name%"
        user:     "%civicrmorg_database_user%"
        password: "%civicrmorg_database_password%"
        charset:  UTF8

doctrine_cache:
  providers:
    memberships_provider:
      ## Why sqlite3? No extra installation; works in any single-server deployments; don't need high performance.
      sqlite3:
         file_name: '%kernel.cache_dir%/memberships.sqlite3'
         table_name: 'cache_memberships'

services:
  memberships.checker:
    class: Civi\MemberStatusBundle\MembershipChecker
    calls:
      - [setContainer, ['@service_container']]
      - [setSourceId, ['%memberships_source%']]

  ## Check memberships by sending HTTP query to civicrm.org DB (with caching).
  memberships.civicrmorg_http:
    class: Civi\MemberStatusBundle\Reader\CachedReaderFactory
    arguments: ['@memberships.civicrmorg_http_uncached', '@doctrine_cache.providers.memberships_provider', '%memberships_ttl%']

  ## Check memberships by sending HTTP query to civicrm.org DB (without caching).
  memberships.civicrmorg_http_uncached:
    class: Civi\MemberStatusBundle\Reader\WebServiceReader
    calls:
      - [setUrl, ['https://cxn.civicrm.org/memberstatus/find']]
      - [setToken, ['%civicrmorg_url_token%']]

  ## Check memberships by sending SQL query to civicrm.org DB.
  ## Query should return columns "url", "via_port", "is_active".
  memberships.civicrmorg_sql:
    class: Civi\MemberStatusBundle\Reader\CivicrmSqlReader
    arguments:
      - @doctrine.dbal.civicrmorg_connection

  ## Check memberships using a CSV file.
  ## The file should have columns "url", "via_port", "is_active".
  memberships.csv:
    class: Ddeboer\DataImport\Reader\CsvReader
    arguments:
      - "%kernel.root_dir%/config/memberships.csv"

  ## Check memberships using a built-in list of domains
  ## This should have columns "url", "via_port", "is_active".
  memberships.static:
    class: Ddeboer\DataImport\Reader\ArrayReader
    arguments:
      -
        -
          url: 'http://dmaster.l'
          is_active: 1
          via_port:
        -
          url: 'https://d46.l'
          is_active: 1
          via_port:
        -
          url: 'http://wpmaster.l'
          is_active: 1
          via_port:
        -
          url: 'http://wp46.l'
          is_active: 1
          via_port:
        -
          url: 'http://via-example-1.l'
          is_active: 1
          via_port: 'example-1.com:123'
